# Read the documentation: https://symfony.com/doc/master/bundles/FOSRestBundle/index.html
# Read the documentation: https://symfony.com/doc/master/bundles/FOSRestBundle/index.html
fos_rest:
    routing_loader:
        default_format: json
        include_format: false
    body_listener: true
    format_listener:
        rules:
            - { path: '^/api', priorities: ['json','html'], fallback_format: html, prefer_extension: false } #TODO: cambiar a solo json en priorities
            - { path: '^/', priorities: ['html'], fallback_format: html, prefer_extension: false }            
    param_fetcher_listener: true
    access_denied_listener:
        json: true
    view:
        view_response_listener: 'force'
        formats:
            json: true