parameters:
    mail.noreply: "%env(MAIL_NOREPLY)%"
    mail.sender_name: "rfchallenge"
    mail.transport: smtp
    mail.username: '%env(MAIL_USERNAME)%'
    mail.password: '%env(MAIL_PASSWORD)%'
    mail.encryption: ssl
    mail.host: '%env(MAIL_HOST)%'
    mail.port: 465
    mail.auth_mode: login
        
    